SAMREF.FILE: SAMREF.PF
ARTIPROV.FILE: ARTIPROV.PF SAMREF.FILE
PROVIDER.FILE: PROVIDER.PF SAMREF.FILE
ART201D.FILE:  art201d.dspf ARTIPROV.FILE PROVIDER.FILE ARTICLE.FILE
ARTICLE.FILE: ARTICLE.PF

IGNORE.PGM: ignore.pgm.rpgle ART201D.FILE
INCLUDE.PGM: include.pgm.rpgle ART201D.FILE